#!/bin/sh
 
# usage: startAdopt <algorithm> <problem-type> <input-file> <debug-level>
# will write log information to ./Logs
# hint: make sure ./Logs file exists!

echo "usage: startAdopt <algorithm> <problem-type> <input-file> <debug-level>"

java -classpath /home/modi/teamcore/code/Adopt -DAdoptDebug=$4 adopt.solver.Simulator $1 $2 $3

