#traffic light agents Makefile
all: 
	@echo == Building traffic light agents ==
	@make -C basic  
	@make -C dcop  
	@make -C greedy
	@make -C qlearning  
	@make -C random
	@make -C supervised_learning
	@make -C WLU
	@echo =================
	@echo

clean:
	@echo == Cleaning all traffic light agents ==
	@make clean -C basic  
	@make clean -C dcop  
	@make clean -C greedy
	@make clean -C qlearning  
	@make clean -C random
	@make clean -C supervised_learning	
	@make clean -C WLU
	@echo =================
